SET TERM ^;

CREATE TRIGGER TRG_BIVENTAS FOR VENTAS
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
    /* SETEO LA FECHA DEL SERVIDOR PARA CADA VENTA INSERTADA */ 
    NEW.ID_VENTA = GEN_ID(GEN_VENTAS_ID, 1);
    NEW.FECHA = CURRENT_DATE;
    NEW.ESTADO = 1;/*POR AHORA, TODAS LAS FACTURAS ESTAN CERRADAS*/

END^

SET TERM ;^
