SET TERM ^ ;
ALTER TRIGGER TRG_BICLIENTES ACTIVE
BEFORE insert POSITION 0
AS
BEGIN
    /* GENERO ID Y SETEO SALDO INICIAL DEL CLIENTE A CERO */ 
    NEW.ID_CLIENTE = GEN_ID(GEN_CLIENTES_ID, 1);
    NEW.SALDO = 0;
END^
SET TERM ; ^
