CREATE TABLE CLIENTES (
    ID_CLIENTE INTEGER NOT NULL,
    NOMBRE_CLIENTE VARCHAR(100) NOT NULL,
    SALDO FLOAT NOT NULL,
    CONSTRAINT PK_CLIENTES PRIMARY KEY (ID_CLIENTE)
);

CREATE TABLE PRODUCTOS (
    ID_PRODUCTO INTEGER NOT NULL,
    DESCRIPCION VARCHAR(100) NOT NULL,
    PRECIO FLOAT NOT NULL,
    CONSTRAINT PK_PRODUCTOS PRIMARY KEY (ID_PRODUCTO)
);

CREATE TABLE VENTAS (
    ID_VENTA INTEGER NOT NULL,
    ID_CLIENTE INTEGER NOT NULL,
    FECHA DATE NOT NULL,
    CONSTRAINT PK_VENTAS PRIMARY KEY (ID_VENTA),
    CONSTRAINT FK_VENTAS_CLIENTES FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE)
);

CREATE TABLE DETALLE_VENTAS (
    ID_PRODUCTO INTEGER NOT NULL,
    ID_VENTA INTEGER NOT NULL,
    CANTIDAD_PRODUCTO FLOAT NOT NULL,
    SUBTOTAL_VENTA FLOAT NOT NULL,
    CONSTRAINT PK_DETALLE_VENTAS PRIMARY KEY (ID_PRODUCTO,ID_VENTA),
    CONSTRAINT FK_DETALLE_VENTAS_VENTAS FOREIGN KEY (ID_VENTA) REFERENCES VENTAS (ID_VENTA),
    CONSTRAINT FK_DETALLE_VENTA_PRODUCTO FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS(ID_PRODUCTO)
);

ALTER TABLE VENTAS ADD ESTADO INT NOT NULL;
ALTER TABLE PRODUCTOS ADD STOCK FLOAT NOT NULL;

DROP TABLE PRODUCTOS;

SELECT r.ID_VENTA, r.ID_CLIENTE, r.FECHA, r.ESTADO
FROM VENTAS r