SET TERM ^ ;
ALTER TRIGGER TRG_BIDETALLE_VENTAS ACTIVE
BEFORE insert POSITION 0
AS
BEGIN
    /*VERIFICAR CANTIDAD DE PRODUCTO INGRESADO(SE HACE DESDE JAVA)*/
    IF(NEW.CANTIDAD_PRODUCTO <= 0) THEN
    EXCEPTION EX_DETALLE1;
    /*VERIFICO STOCK DE PRODUCTO(SE HACE DESDE JAVA)*/
    IF (NEW.CANTIDAD_PRODUCTO >
    (SELECT P.STOCK FROM PRODUCTOS P WHERE
    P.ID_PRODUCTO = NEW.ID_PRODUCTO))THEN
    EXCEPTION EX_PRODUCTOS3;
    /*ACTUALIZO SUBTOTAL EN DETALLE_VENTAS*/
    NEW.SUBTOTAL_VENTA = 
    (NEW.CANTIDAD_PRODUCTO * (SELECT P.PRECIO FROM
    PRODUCTOS P WHERE 
    NEW.ID_PRODUCTO = P.ID_PRODUCTO));  
END^
SET TERM ; ^
