SET TERM ^ ;
ALTER TRIGGER TRG_BUPRODUCTOS ACTIVE
BEFORE update POSITION 0
AS
BEGIN
    IF(NEW.ID_PRODUCTO <> OLD.ID_PRODUCTO) THEN
    EXCEPTION EX_PRODUCTOS4;
    /*VERIFICAR QUE NO SE INGRESE PRECIO NEGATIVO*/
    IF(NEW.PRECIO <= 0) THEN
    EXCEPTION EX_PRODUCTOS5;
    /*VERIFICAR STOCK NEGATIVO*/
    IF(NEW.STOCK < 0) THEN
    EXCEPTION EX_PRODUCTOS6;
END^
SET TERM ; ^
