SET TERM ^ ;
ALTER TRIGGER TRG_AIDETALLE_VENTAS ACTIVE
AFTER insert POSITION 0
AS
BEGIN
    /* ACTUALIZO STOCK PRODUCTOS*/
    UPDATE PRODUCTOS P SET 
    P.STOCK = P.STOCK - NEW.CANTIDAD_PRODUCTO  WHERE 
    P.ID_PRODUCTO = NEW.ID_PRODUCTO; 
    /*ACTUALIZO SALDO CLIENTE*/     
    UPDATE CLIENTES C SET C.SALDO = 
    C.SALDO + NEW.SUBTOTAL_VENTA
    WHERE C.ID_CLIENTE = 
    (SELECT V.ID_CLIENTE FROM VENTAS V WHERE
    V.ESTADO = 0);    
      
END^
SET TERM ; ^
